include: package:flutter_lints/flutter.yaml

linter:
  rules:
    avoid_print: false  # Allow print for debugging in this specific project context
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    prefer_final_locals: true
    use_key_in_widget_constructors: true
